version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_volume_data:/data

    # 作用：redis可视化
    redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      -./redis_insight_volume_data:/data

volumes:
  redis_volume_data:
  redis_insight_volume_data: